### ISSUE TITLE
v 0.0.1 #16 crashes on iPhone 5 ios6 when trailhead selected

### ISSUE THREAD

**Issue by gwpangloss** [opentraildata/OpenTrails-Mobile#129] opened 2014-05-13 14:43 UTC
When selecting a trailhead from map or from "search" view, app shows attempt to change icon, crashes, returns iPhone to "desktop" view.  No error message.

iPhone 4s with ios7 works slowly, but is "GO," including returning to TTT after getting directions.

**Comment by alanjosephwilliams** [comment] 2014-05-13 17:12
Thanks for documenting this problem, Paul. We will have to investigate what changed between the last release and now that could be causing this. 

Apologies for ignorance, but could you explain "GO"?

@rclosner

**Comment by gwpangloss** [comment] 2014-05-13 17:36
Cool.  Oh, sorry, it's a boolean term they use it in the military.  If something is "GO" or "NO-GO," it's good, or it's bad.

**Comment by anselmbradford** [comment] 2014-05-21 06:11
Crashes for me on my iPod running iOS 6.1.2., but I can't reproduce it consistently. It's crashed intermittently when:
- clicking a trailhead.
- closing the trails detail view.
- expanding and contracting the trails detail view.
- clicking a filter in the search view.
- clicking a trail in the search view results list.
- clicking the geolocate button.
- clicking the search button.

So pretty much intermittently all over the place. It looks like a plain old memory issue. If I give a long pause between each click I can navigate around the app, but any fast clicking takes it down where ever I am. 

Also, there's a flash of the agency screen on first app load.

**Comment by alanjosephwilliams** [comment] 2014-05-21 19:31
Paul--could you give us an update on your two devices?

**Comment by gwpangloss** [comment] 2014-05-22 15:47
Tested good.  The problem has been resolved.

**Closed as completed** 2014-06-04 15:44 UTC
